"""Winwing MCDU constants
"""

from enum import Enum, IntEnum


class MCDU_DEVICE_MASKS(IntEnum):
    NONE = 0
    MCDU = 0x01
    CAP = 0x10
    FO = 0x20
    OBS = 0x40
    # PFP3N = 0x02
    # PFP4 = 0x04
    # PFP7 = 0x08


class MCDU_BRIGHTNESS(Enum):
    BACKLIGHT = 0  # 0 .. 255
    SCREEN_BACKLIGHT = 1  # 0 .. 255


class MCDU_ANNUNCIATORS(Enum):
    FAIL = 8
    FM = 9
    MCDU = 10
    MENU = 11
    FM1 = 12
    IND = 13
    RDY = 14
    STATUS = 15
    FM2 = 16


class MCDU_COLORS(Enum):
    AMBER = "a"
    BLUE = "b"  # cyan
    GREEN = "g"
    GREY = "e"
    GW = "Gw"
    LW = "Lw"
    MAGENTA = "m"
    RED = "r"
    SPECIAL = "s"
    WHITE = "w"
    YELLOW = "y"


COLOR_MAP = {
    "L": 0x0000,  # black with grey background
    "A": 0x0021,  # amber
    "W": 0x0042,  # white
    "B": 0x0063,  # cyan
    "G": 0x0084,  # green
    "M": 0x00A5,  # magenta
    "R": 0x00C6,  # red
    "Y": 0x00E7,  # yellow
    "E": 0x0108,  # grey
    " ": 0x0042,  # use white
}


MCDU_TERM_COLORS = {
    "a": "\033[38;5;208m",  # amber, dark yellow
    "b": "\033[38;5;39m",
    "g": "\033[38;5;46m",
    "m": "\033[38;5;165m",
    "w": "\033[38;5;231m",
    "y": "\033[38;5;226m",
    "s": "\033[38;5;196m",  # special characters, not a color
    "Lw": "\033[38;5;15m",  # bold white, bright white
    "Lg": "\033[38;5;10m",  # bold white, bright green
}


class MCDU_COLOR(Enum):
    AMBER = "a"
    BLUE = "b"
    CYAN = "b"
    MAGENTA = "m"
    WHITE = "w"
    GREEN = "g"
    DEFAULT = "w"
    YELLOW = "y"
    SPECIAL = "s"
    L_WHITE = "Lw"
    L_GREEN = "Lg"


# Constants
PAGE_LINES = 14  # Header + 6 * label + 6 * cont + textbox
PAGE_CHARS_PER_LINE = 24
PAGE_BYTES_PER_CHAR = 3
PAGE_BYTES_PER_LINE = PAGE_CHARS_PER_LINE * PAGE_BYTES_PER_CHAR
PAGE_BYTES_PER_PAGE = PAGE_BYTES_PER_LINE * PAGE_LINES

MCDU_DISPLAY_DATAREFS_A339 = [
    # ("AirbusFBW/MCDU1titleb", None),
    ("AirbusFBW/MCDU1titleg", None),
    ("AirbusFBW/MCDU1titles", None),
    ("AirbusFBW/MCDU1titlew", None),
    # ("AirbusFBW/MCDU1titley", None),
    ("AirbusFBW/MCDU1stitley", None),
    ("AirbusFBW/MCDU1stitlew", None),
    ("AirbusFBW/MCDU1label1w", None),
    ("AirbusFBW/MCDU1label2w", None),
    ("AirbusFBW/MCDU1label3w", None),
    ("AirbusFBW/MCDU1label4w", None),
    ("AirbusFBW/MCDU1label5w", None),
    ("AirbusFBW/MCDU1label6w", None),
    # ("AirbusFBW/MCDU1label1a", None),
    ("AirbusFBW/MCDU1label2a", None),
    ("AirbusFBW/MCDU1label3a", None),
    # ("AirbusFBW/MCDU1label4a", None),
    # ("AirbusFBW/MCDU1label5a", None),
    ("AirbusFBW/MCDU1label6a", None),
    ("AirbusFBW/MCDU1label1g", None),
    ("AirbusFBW/MCDU1label2g", None),
    ("AirbusFBW/MCDU1label3g", None),
    ("AirbusFBW/MCDU1label4g", None),
    ("AirbusFBW/MCDU1label5g", None),
    # ("AirbusFBW/MCDU1label6g", None),
    ("AirbusFBW/MCDU1label1b", None),
    # ("AirbusFBW/MCDU1label2b", None),
    ("AirbusFBW/MCDU1label3b", None),
    ("AirbusFBW/MCDU1label4b", None),
    ("AirbusFBW/MCDU1label5b", None),
    ("AirbusFBW/MCDU1label6b", None),
    # ("AirbusFBW/MCDU1label1y", None),
    # ("AirbusFBW/MCDU1label2y", None),
    # ("AirbusFBW/MCDU1label3y", None),
    # ("AirbusFBW/MCDU1label4y", None),
    # ("AirbusFBW/MCDU1label5y", None),
    ("AirbusFBW/MCDU1label6y", None),
    ("AirbusFBW/MCDU1label1Lg", None),
    ("AirbusFBW/MCDU1label2Lg", None),
    ("AirbusFBW/MCDU1label3Lg", None),
    ("AirbusFBW/MCDU1label4Lg", None),
    ("AirbusFBW/MCDU1label5Lg", None),
    ("AirbusFBW/MCDU1label6Lg", None),
    ("AirbusFBW/MCDU1cont1b", None),
    ("AirbusFBW/MCDU1cont2b", None),
    ("AirbusFBW/MCDU1cont3b", None),
    ("AirbusFBW/MCDU1cont4b", None),
    ("AirbusFBW/MCDU1cont5b", None),
    ("AirbusFBW/MCDU1cont6b", None),
    ("AirbusFBW/MCDU1cont1m", None),
    ("AirbusFBW/MCDU1cont2m", None),
    ("AirbusFBW/MCDU1cont3m", None),
    # ("AirbusFBW/MCDU1cont4m", None),
    # ("AirbusFBW/MCDU1cont5m", None),
    ("AirbusFBW/MCDU1cont6m", None),
    ("AirbusFBW/MCDU1scont1m", None),
    ("AirbusFBW/MCDU1scont2m", None),
    ("AirbusFBW/MCDU1scont3m", None),
    ("AirbusFBW/MCDU1scont4m", None),
    ("AirbusFBW/MCDU1scont5m", None),
    ("AirbusFBW/MCDU1scont6m", None),
    ("AirbusFBW/MCDU1cont1a", None),
    ("AirbusFBW/MCDU1cont2a", None),
    ("AirbusFBW/MCDU1cont3a", None),
    ("AirbusFBW/MCDU1cont4a", None),
    ("AirbusFBW/MCDU1cont5a", None),
    ("AirbusFBW/MCDU1cont6a", None),
    ("AirbusFBW/MCDU1scont1a", None),
    ("AirbusFBW/MCDU1scont2a", None),
    ("AirbusFBW/MCDU1scont3a", None),
    ("AirbusFBW/MCDU1scont4a", None),
    ("AirbusFBW/MCDU1scont5a", None),
    ("AirbusFBW/MCDU1scont6a", None),
    ("AirbusFBW/MCDU1cont1w", None),
    ("AirbusFBW/MCDU1cont2w", None),
    ("AirbusFBW/MCDU1cont3w", None),
    ("AirbusFBW/MCDU1cont4w", None),
    ("AirbusFBW/MCDU1cont5w", None),
    ("AirbusFBW/MCDU1cont6w", None),
    ("AirbusFBW/MCDU1cont1g", None),
    ("AirbusFBW/MCDU1cont2g", None),
    ("AirbusFBW/MCDU1cont3g", None),
    ("AirbusFBW/MCDU1cont4g", None),
    ("AirbusFBW/MCDU1cont5g", None),
    ("AirbusFBW/MCDU1cont6g", None),
    # ("AirbusFBW/MCDU1cont1c", None),
    # ("AirbusFBW/MCDU1cont2c", None),
    # ("AirbusFBW/MCDU1cont3c", None),
    # ("AirbusFBW/MCDU1cont4c", None),
    # ("AirbusFBW/MCDU1cont5c", None),
    # ("AirbusFBW/MCDU1cont6c", None),
    ("AirbusFBW/MCDU1scont1g", None),
    ("AirbusFBW/MCDU1scont2g", None),
    ("AirbusFBW/MCDU1scont3g", None),
    ("AirbusFBW/MCDU1scont4g", None),
    ("AirbusFBW/MCDU1scont5g", None),
    ("AirbusFBW/MCDU1scont6g", None),
    ("AirbusFBW/MCDU1cont1s", None),
    ("AirbusFBW/MCDU1cont2s", None),
    ("AirbusFBW/MCDU1cont3s", None),
    ("AirbusFBW/MCDU1cont4s", None),
    ("AirbusFBW/MCDU1cont5s", None),
    ("AirbusFBW/MCDU1cont6s", None),
    ("AirbusFBW/MCDU1scont1b", None),
    ("AirbusFBW/MCDU1scont2b", None),
    ("AirbusFBW/MCDU1scont3b", None),
    ("AirbusFBW/MCDU1scont4b", None),
    ("AirbusFBW/MCDU1scont5b", None),
    ("AirbusFBW/MCDU1scont6b", None),
    ("AirbusFBW/MCDU1cont1y", None),
    ("AirbusFBW/MCDU1cont2y", None),
    ("AirbusFBW/MCDU1cont3y", None),
    ("AirbusFBW/MCDU1cont4y", None),
    ("AirbusFBW/MCDU1cont5y", None),
    ("AirbusFBW/MCDU1cont6y", None),
    ("AirbusFBW/MCDU1scont1w", None),
    ("AirbusFBW/MCDU1scont2w", None),
    ("AirbusFBW/MCDU1scont3w", None),
    ("AirbusFBW/MCDU1scont4w", None),
    ("AirbusFBW/MCDU1scont5w", None),
    ("AirbusFBW/MCDU1scont6w", None),
    ("AirbusFBW/MCDU1scont1y", None),
    ("AirbusFBW/MCDU1scont2y", None),
    ("AirbusFBW/MCDU1scont3y", None),
    ("AirbusFBW/MCDU1scont4y", None),
    # ("AirbusFBW/MCDU1scont5y", None),
    # ("AirbusFBW/MCDU1scont6y", None),
    ("AirbusFBW/MCDU1spw", 4),  # textbox
    ("AirbusFBW/MCDU1spa", None),  # textbox
]

MCDU_NO_DISPLAY_DATAREFS_A339 = [
    ("AirbusFBW/MCDU1VertSlewKeys", None),
    ("AirbusFBW/PanelBrightnessLevel", None),
    ("AirbusFBW/DUBrightness[6]", None),
    ("AirbusFBW/DUBrightness[7]", None),
]


# #######################################@
# Collection
#
MCDU_DISPLAY_DATAREFS = {
    "A321": MCDU_DISPLAY_DATAREFS_A339,
    "A21N": MCDU_DISPLAY_DATAREFS_A339,
    "A319": MCDU_DISPLAY_DATAREFS_A339,
    "A320": MCDU_DISPLAY_DATAREFS_A339,
    "A339": MCDU_DISPLAY_DATAREFS_A339,
    "A350": MCDU_DISPLAY_DATAREFS_A339,
}

MCDU_NO_DISPLAY_DATAREFS = {
    "A321": MCDU_NO_DISPLAY_DATAREFS_A339,
    "A21N": MCDU_NO_DISPLAY_DATAREFS_A339,
    "A319": MCDU_NO_DISPLAY_DATAREFS_A339,
    "A320": MCDU_NO_DISPLAY_DATAREFS_A339,
    "A339": MCDU_NO_DISPLAY_DATAREFS_A339,
    "A350": MCDU_NO_DISPLAY_DATAREFS_A339,
}

AIRCRAFT_DATAREF = "sim/aircraft/view/acf_ICAO"
VALID_ICAO_AIRCRAFTS = set(MCDU_DISPLAY_DATAREFS.keys())


# List of datarefs without led connection to request
# Text Dataref format:  <MCDU[1,2]><Line[title/label/cont/etc]><Linenumber[1...6]><Color[a,b,m,s,w,y]>.
# We must read all 25 Bytes per dataref!


# List of MCDU keys
class ButtonType(Enum):
    SWITCH = 0
    TOGGLE = 1
    NONE = 5


class DrefType(Enum):
    DATA = 0
    CMD = 1
    NONE = 2


MDCU_KEYS_A339 = [
    [0, "LSK1L", "AirbusFBW/MCDU1LSK1L", DrefType.CMD, ButtonType.TOGGLE],
    [1, "LSK2L", "AirbusFBW/MCDU1LSK2L", DrefType.CMD, ButtonType.TOGGLE],
    [2, "LSK3L", "AirbusFBW/MCDU1LSK3L", DrefType.CMD, ButtonType.TOGGLE],
    [3, "LSK4L", "AirbusFBW/MCDU1LSK4L", DrefType.CMD, ButtonType.TOGGLE],
    [4, "LSK5L", "AirbusFBW/MCDU1LSK5L", DrefType.CMD, ButtonType.TOGGLE],
    [5, "LSK6L", "AirbusFBW/MCDU1LSK6L", DrefType.CMD, ButtonType.TOGGLE],
    [6, "LSK1R", "AirbusFBW/MCDU1LSK1R", DrefType.CMD, ButtonType.TOGGLE],
    [7, "LSK2R", "AirbusFBW/MCDU1LSK2R", DrefType.CMD, ButtonType.TOGGLE],
    [8, "LSK3R", "AirbusFBW/MCDU1LSK3R", DrefType.CMD, ButtonType.TOGGLE],
    [9, "LSK4R", "AirbusFBW/MCDU1LSK4R", DrefType.CMD, ButtonType.TOGGLE],
    [10, "LSK5R", "AirbusFBW/MCDU1LSK5R", DrefType.CMD, ButtonType.TOGGLE],
    [11, "LSK6R", "AirbusFBW/MCDU1LSK6R", DrefType.CMD, ButtonType.TOGGLE],  # 0x800
    [12, "DIRTO", "AirbusFBW/MCDU1DirTo", DrefType.CMD, ButtonType.TOGGLE],
    [13, "PROG", "AirbusFBW/MCDU1Prog", DrefType.CMD, ButtonType.TOGGLE],
    [14, "PERF", "AirbusFBW/MCDU1Perf", DrefType.CMD, ButtonType.TOGGLE],
    [15, "INIT", "AirbusFBW/MCDU1Init", DrefType.CMD, ButtonType.TOGGLE],
    [16, "DATA", "AirbusFBW/MCDU1Data", DrefType.CMD, ButtonType.TOGGLE],
    [17, "MENU1", "toliss_airbus/iscs_open", DrefType.CMD, ButtonType.TOGGLE],  # 17 emtpy, map to open ICSC screen
    [18, "BRT", "AirbusFBW/MCDU1KeyBright", DrefType.CMD, ButtonType.TOGGLE],
    [19, "FPLN", "AirbusFBW/MCDU1Fpln", DrefType.CMD, ButtonType.TOGGLE],
    [20, "RADNAV", "AirbusFBW/MCDU1RadNav", DrefType.CMD, ButtonType.TOGGLE],
    [21, "FUEL", "AirbusFBW/MCDU1FuelPred", DrefType.CMD, ButtonType.TOGGLE],
    [22, "SEC-FPLN", "AirbusFBW/MCDU1SecFpln", DrefType.CMD, ButtonType.TOGGLE],
    [23, "ATC", "AirbusFBW/MCDU1ATC", DrefType.CMD, ButtonType.TOGGLE],
    [24, "MENU", "AirbusFBW/MCDU1Menu", DrefType.CMD, ButtonType.TOGGLE],
    [25, "DIM", "AirbusFBW/MCDU1KeyDim", DrefType.CMD, ButtonType.TOGGLE],
    [26, "AIRPORT", "AirbusFBW/MCDU1Airport", DrefType.CMD, ButtonType.TOGGLE],
    [27, "MENU2", "AirbusFBW/purser/fwd", DrefType.CMD, ButtonType.TOGGLE],  # 27 empty, map to switch MCDU
    [28, "SLEW_LEFT", "AirbusFBW/MCDU1SlewLeft", DrefType.CMD, ButtonType.TOGGLE],
    [29, "SLEW_UP", "AirbusFBW/MCDU1SlewUp", DrefType.CMD, ButtonType.TOGGLE],
    [30, "SLEW_RIGHT", "AirbusFBW/MCDU1SlewRight", DrefType.CMD, ButtonType.TOGGLE],
    [31, "SLEW_DOWN", "AirbusFBW/MCDU1SlewDown", DrefType.CMD, ButtonType.TOGGLE],
    [32, "KEY1", "AirbusFBW/MCDU1Key1", DrefType.CMD, ButtonType.TOGGLE],
    [33, "KEY2", "AirbusFBW/MCDU1Key2", DrefType.CMD, ButtonType.TOGGLE],
    [34, "KEY3", "AirbusFBW/MCDU1Key3", DrefType.CMD, ButtonType.TOGGLE],
    [35, "KEY4", "AirbusFBW/MCDU1Key4", DrefType.CMD, ButtonType.TOGGLE],
    [36, "KEY5", "AirbusFBW/MCDU1Key5", DrefType.CMD, ButtonType.TOGGLE],
    [37, "KEY6", "AirbusFBW/MCDU1Key6", DrefType.CMD, ButtonType.TOGGLE],
    [38, "KEY7", "AirbusFBW/MCDU1Key7", DrefType.CMD, ButtonType.TOGGLE],
    [39, "KEY8", "AirbusFBW/MCDU1Key8", DrefType.CMD, ButtonType.TOGGLE],
    [40, "KEY9", "AirbusFBW/MCDU1Key9", DrefType.CMD, ButtonType.TOGGLE],
    [41, "DOT", "AirbusFBW/MCDU1KeyDecimal", DrefType.CMD, ButtonType.TOGGLE],
    [42, "KEY0", "AirbusFBW/MCDU1Key0", DrefType.CMD, ButtonType.TOGGLE],
    [43, "PLUSMINUS", "AirbusFBW/MCDU1KeyPM", DrefType.CMD, ButtonType.TOGGLE],
    [44, "KEYA", "AirbusFBW/MCDU1KeyA", DrefType.CMD, ButtonType.TOGGLE],
    [45, "KEYB", "AirbusFBW/MCDU1KeyB", DrefType.CMD, ButtonType.TOGGLE],
    [46, "KEYC", "AirbusFBW/MCDU1KeyC", DrefType.CMD, ButtonType.TOGGLE],
    [47, "KEYD", "AirbusFBW/MCDU1KeyD", DrefType.CMD, ButtonType.TOGGLE],
    [48, "KEYE", "AirbusFBW/MCDU1KeyE", DrefType.CMD, ButtonType.TOGGLE],
    [49, "KEYF", "AirbusFBW/MCDU1KeyF", DrefType.CMD, ButtonType.TOGGLE],
    [50, "KEYG", "AirbusFBW/MCDU1KeyG", DrefType.CMD, ButtonType.TOGGLE],
    [51, "KEYH", "AirbusFBW/MCDU1KeyH", DrefType.CMD, ButtonType.TOGGLE],
    [52, "KEYI", "AirbusFBW/MCDU1KeyI", DrefType.CMD, ButtonType.TOGGLE],
    [53, "KEYJ", "AirbusFBW/MCDU1KeyJ", DrefType.CMD, ButtonType.TOGGLE],
    [54, "KEYK", "AirbusFBW/MCDU1KeyK", DrefType.CMD, ButtonType.TOGGLE],
    [55, "KEYL", "AirbusFBW/MCDU1KeyL", DrefType.CMD, ButtonType.TOGGLE],
    [56, "KEYM", "AirbusFBW/MCDU1KeyM", DrefType.CMD, ButtonType.TOGGLE],
    [57, "KEYN", "AirbusFBW/MCDU1KeyN", DrefType.CMD, ButtonType.TOGGLE],
    [58, "KEYO", "AirbusFBW/MCDU1KeyO", DrefType.CMD, ButtonType.TOGGLE],
    [59, "KEYP", "AirbusFBW/MCDU1KeyP", DrefType.CMD, ButtonType.TOGGLE],
    [60, "KEYQ", "AirbusFBW/MCDU1KeyQ", DrefType.CMD, ButtonType.TOGGLE],
    [61, "KEYR", "AirbusFBW/MCDU1KeyR", DrefType.CMD, ButtonType.TOGGLE],
    [62, "KEYS", "AirbusFBW/MCDU1KeyS", DrefType.CMD, ButtonType.TOGGLE],
    [63, "KEYT", "AirbusFBW/MCDU1KeyT", DrefType.CMD, ButtonType.TOGGLE],
    [64, "KEYU", "AirbusFBW/MCDU1KeyU", DrefType.CMD, ButtonType.TOGGLE],
    [65, "KEYV", "AirbusFBW/MCDU1KeyV", DrefType.CMD, ButtonType.TOGGLE],
    [66, "KEYW", "AirbusFBW/MCDU1KeyW", DrefType.CMD, ButtonType.TOGGLE],
    [67, "KEYX", "AirbusFBW/MCDU1KeyX", DrefType.CMD, ButtonType.TOGGLE],
    [68, "KEYY", "AirbusFBW/MCDU1KeyY", DrefType.CMD, ButtonType.TOGGLE],
    [69, "KEYZ", "AirbusFBW/MCDU1KeyZ", DrefType.CMD, ButtonType.TOGGLE],
    [70, "SLASH", "AirbusFBW/MCDU1KeySlash", DrefType.CMD, ButtonType.TOGGLE],
    [71, "SPACE", "AirbusFBW/MCDU1KeySpace", DrefType.CMD, ButtonType.TOGGLE],
    [72, "OVERFLY", "AirbusFBW/MCDU1KeyOverfly", DrefType.CMD, ButtonType.TOGGLE],
    [73, "Clear", "AirbusFBW/MCDU1KeyClear", DrefType.CMD, ButtonType.TOGGLE],
    [75, "LCDBright1", "AirbusFBW/DUBrightness[6]", DrefType.DATA, ButtonType.NONE, MCDU_BRIGHTNESS.SCREEN_BACKLIGHT],
    [75, "LCDBright2", "AirbusFBW/DUBrightness[7]", DrefType.DATA, ButtonType.NONE, MCDU_BRIGHTNESS.SCREEN_BACKLIGHT],
    [75, "Backlight", "AirbusFBW/PanelBrightnessLevel", DrefType.DATA, ButtonType.NONE, MCDU_BRIGHTNESS.BACKLIGHT],
]

MDCU_KEYS = {
    "A321": MDCU_KEYS_A339,
    "A21N": MDCU_KEYS_A339,
    "A319": MDCU_KEYS_A339,
    "A320": MDCU_KEYS_A339,
    "A339": MDCU_KEYS_A339,
    "A350": MDCU_KEYS_A339,
}


MDCU_UNITS = {
    "A321": {1, 2},
    "A21N": {1, 2},
    "A319": {1, 2},
    "A320": {1, 2},
    "A339": {1, 2},
    "A350": {1, 2},
}


def MCDU_INIT_SEQUENCE(background_color: list) -> list:
    return [
        [
            0xF0,
            0x0,
            0x1,
            0x38,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x1E,
            0x1,
            0x0,
            0x0,
            0xC4,
            0x24,
            0xA,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x18,
            0x1,
            0x0,
            0x0,
            0xC4,
            0x24,
            0xA,
            0x0,
            0x0,
            0x8,
            0x0,
            0x0,
            0x0,
            0x34,
            0x0,
            0x18,
            0x0,
            0xE,
            0x0,
            0x18,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0xC4,
            0x24,
            0xA,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x2,
            0x38,
            0x0,
            0x0,
            0x0,
            0x1,
            0x0,
            0x5,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0xC4,
            0x24,
            0xA,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x1,
            0x0,
            0x6,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x3,
            0x38,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x0,
            0x0,
            0x0,
            0xFF,
            0x4,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x0,
            0xA5,
            0xFF,
            0xFF,
            0x5,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x4,
            0x38,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0xFF,
            0xFF,
            0xFF,
            0xFF,
            0x6,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0xFF,
            0xFF,
            0x0,
            0xFF,
            0x7,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x5,
            0x38,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x3D,
            0xFF,
            0x0,
            0xFF,
            0x8,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0xFF,
            0x63,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x6,
            0x38,
            0xFF,
            0xFF,
            0x9,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x0,
            0x0,
            0xFF,
            0xFF,
            0xA,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x7,
            0x38,
            0x0,
            0x0,
            0x2,
            0x0,
            0x0,
            0xFF,
            0xFF,
            0xFF,
            0xB,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x42,
            0x5C,
            0x61,
            0xFF,
            0xC,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x8,
            0x38,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x77,
            0x77,
            0x77,
            0xFF,
            0xD,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x2,
            0x0,
            0x5E,
            0x73,
            0x79,
            0xFF,
            0xE,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x9,
            0x38,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            background_color[0],
            background_color[1],
            background_color[2],
            0xFF,
            0xF,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x0,
            0xA5,
            0xFF,
            0xFF,
            0x10,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xA,
            0x38,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0xFF,
            0xFF,
            0xFF,
            0xFF,
            0x11,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0xFF,
            0xFF,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xB,
            0x38,
            0xFF,
            0x12,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x3D,
            0xFF,
            0x0,
            0xFF,
            0x13,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xC,
            0x38,
            0x0,
            0x3,
            0x0,
            0xFF,
            0x63,
            0xFF,
            0xFF,
            0x14,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x0,
            0x0,
            0xFF,
            0xFF,
            0x15,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xD,
            0x38,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x0,
            0xFF,
            0xFF,
            0xFF,
            0x16,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x42,
            0x5C,
            0x61,
            0xFF,
            0x17,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xE,
            0x38,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x77,
            0x77,
            0x77,
            0xFF,
            0x18,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x3,
            0x0,
            0x5E,
            0x73,
            0x79,
            0xFF,
            0x19,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0xF,
            0x38,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x4,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x1A,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x4,
            0x0,
            0x1,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x10,
            0x38,
            0x1B,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x19,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0xE,
            0x0,
            0x0,
            0x0,
            0x4,
            0x0,
            0x2,
            0x0,
            0x0,
            0x0,
            0x1C,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x1A,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0x1,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
        [
            0xF0,
            0x0,
            0x11,
            0x12,
            0x2,
            0x32,
            0xBB,
            0x0,
            0x0,
            0x1C,
            0x1,
            0x0,
            0x0,
            0x76,
            0x72,
            0x19,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
            0x0,
        ],
    ]
